# These are supported funding model platforms

github: [xgqfrms]
patreon: xgqfrms
open_collective: xgqfrms
ko_fi: xgqfrms
tidelift: npm/cdn
# community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
# liberapay: # Replace with a single Liberapay username
issuehunt: xgqfrms
# otechie: # Replace with a single Otechie username
custom: custom: ["https://www.paypal.me/xgqfrms", xgqfrms.xyz]
